const IDENTIFIER_SIZE = 32
const SIGNATURE_SIZE = 65
const SOC_IDENTIFIER_OFFSET = 0
const SOC_SIGNATURE_OFFSET = SOC_IDENTIFIER_OFFSET + IDENTIFIER_SIZE
const SOC_SPAN_OFFSET = SOC_SIGNATURE_OFFSET + SIGNATURE_SIZE

export const SPAN_SIZE = 8
export const SOC_PAYLOAD_OFFSET = SOC_SPAN_OFFSET + SPAN_SIZE
export const MIN_PAYLOAD_SIZE = 1
export const MAX_PAYLOAD_SIZE = 4096
